### PR TITLE
update kubernetes v1.17.1 to v1.21.0

### LINKED ISSUE #99: "make build" fails github.com/openshift/client-go invalid version: unknown revision 1ede333d7ba5
Running ```make build``` fails:

```mkdir -p "bin"
go build -o "bin" "./cmd/extended-platform-tests"
go: k8s.io/kubernetes@v1.17.1 requires
	github.com/openshift/client-go@v0.0.0-20190905095913-1ede333d7ba5: invalid version: unknown revision 1ede333d7ba5
make: *** [Makefile:7: build] Error 1
```

### PR DESCRIPTION
**Pull request by jianzhangbjz**
Fix #99 
```go
[jzhang@dhcp-140-36 openshift-tests]$ make build
mkdir -p "bin"
go build -o "bin" "./cmd/extended-platform-tests"
[jzhang@dhcp-140-36 openshift-tests]$ go version
go version go1.16.3 linux/amd64
```

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
@kuiwang02 Could you help have a review? Thanks!

**Comment by kuiwang02** [comment]
@jianzhangbjz will do it. because I need to do the following at least
1) build it and try it works
2) try to link it in openshift-tests-private to see if the openshift-test-private work

maybe need more time to review it.

**Comment by kuiwang02** [comment]
@jianzhangbjz when executing "make build" on update-kubernetes branch, I find the "github.com/google/go-github v17.0.0+incompatible // indirect" is deleted.
```console
kuiwang@Kuis-MacBook-Pro openshift-tests % git diff
kuiwang@Kuis-MacBook-Pro openshift-tests % make clean;make build
rm -f ./bin/extended-platform-tests
mkdir -p "bin"
go build -o "bin" "./cmd/extended-platform-tests"
kuiwang@Kuis-MacBook-Pro openshift-tests % git diff             
diff --git a/go.mod b/go.mod
index f1782b8e..ced1589d 100644
--- a/go.mod
+++ b/go.mod
@@ -15,7 +15,6 @@ require (
        github.com/ghodss/yaml v1.0.0
        github.com/google/cadvisor v0.35.1-0.20200116204205-4abc562912f0 // indirect
        github.com/google/go-cmp v0.3.1 // indirect
-       github.com/google/go-github v17.0.0+incompatible // indirect
        github.com/googleapis/gnostic v0.3.1 // indirect
        github.com/imdario/mergo v0.3.8 // indirect
        github.com/jteeuwen/go-bindata v3.0.8-0.20151023091102-a0ff2567cfb7+incompatible
kuiwang@Kuis-MacBook-Pro openshift-tests % 
```

so, just double confirm if it is needed or not.

For me, it seems not need it anymore.

**Comment by jianzhangbjz** [comment]
@kuiwang02 Yes, thanks! I have removed it. Could you help give approval? Thanks!

**Pull request merged**
