### PR TITLE
Fix bindata

### PR DESCRIPTION
**Pull request by bandrade**
Fix for issue:
https://github.com/openshift/openshift-tests/issues/7

The solution is composed of the following topics:
- Add example folder from origin that was not migrated
- Update Makefile
- Run `make update` to update bindata

Results:
```
make update
Running `gofmt -s -l -w` on 273 file(s).
ln -s /home/bandrade/go/src/github.com/openshift/extended-platform-tests/vendor "/tmp/tmp.gjsHzzuoSW/src"
export GO111MODULE=off && export GOPATH=/tmp/tmp.gjsHzzuoSW && export GOBIN=/tmp/tmp.gjsHzzuoSW/bin && go install "./vendor/github.com/jteeuwen/go-bindata/..."
/tmp/tmp.gjsHzzuoSW/bin/go-bindata -nocompress -nometadata -prefix "testextended" -pkg "testdata" -o "./test/extended/testdata/bindata.go" -ignore "OWNERS" test/extended/testdata/... examples/... test/integration/testdata/... && gofmt -s -w "./test/extended/testdata/bindata.go"

```

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
@bandrade Good job! @sallyom @soltysh  Could you help review it? Thanks very much!

**Comment by bandrade** [comment]
@jianzhangbjz np, I'm certain that I added more than what is needed to fix, but I'll review and filter right now.

**Comment by bandrade** [comment]
@jianzhangbjz now I think it's ok from my side, I didn't have to add any vendor library, just fix Makefile and add examples directory that was not migrated but required if we want index more yamls.  Can you please review it? Thank you

**Pull request merged**
