### PR TITLE
automation code of olm cases

### PR DESCRIPTION
**Pull request by kuiwang02**
--OCP-24904 OCP-24870 OCP-24076
  --OCP-21484 OCP-25679 OCP-24027
  --OCP-22200 OCP-24906 OCP-21532
  --OCP-21418 OCP-21825 OCP-23170
  --OCP-26002 OCP-25757 OCP-24438
  --OCP-21404 OCP-20979 OCP-22226
  --OCP-23473 OCP-22656 OCP-24664
  --OCP-21824 OCP-24093 OCP-24094
  --OCP-25855 OCP-25783

### CODE REVIEW

**Comment by kuiwang02** [comment]
@jianzhangbjz @bandrade @scolange @tbuskey Please have a review, thanks!

**Comment by kuiwang02** [comment]
```console
08:43:12 Apr 14 20:43:12.044: INFO: Running 'oc --kubeconfig=/root/kubeconf/kubeconfig get packagemanifest -l catalog=certified-operators -o=jsonpath={range .items[*]}{.metadata.labels.catalog}:{.metadata.name}{'\n'}{end}'
08:43:12 Apr 14 20:43:12.509: INFO: Running 'oc --kubeconfig=/root/kubeconf/kubeconfig get packagemanifest -l catalog=redhat-operators -o=jsonpath={range .items[*]}{.metadata.labels.catalog}:{.metadata.name}{'\n'}{end}'
08:43:12 Apr 14 20:43:12.862: INFO: Running 'oc --kubeconfig=/root/kubeconf/kubeconfig get packagemanifest -l catalog=community-operators -o=jsonpath={range .items[*]}{.metadata.labels.catalog}:{.metadata.name}{'\n'}{end}'
08:43:14 I0414 20:43:14.534708   22239 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
08:43:14 I0414 20:43:14.626390   22242 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
08:43:14 started: (0/1/25) "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-23170-API labels should be hash [Suite:openshift/conformance/parallel]"
08:43:14 
08:43:14 started: (0/2/25) "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-24904-create catalogsource with grpc address [Suite:openshift/conformance/parallel]"
08:43:14 
08:43:14 started: (0/3/25) "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-24094-Default resources of Marketplace operator [Suite:openshift/conformance/parallel]"
08:43:14 
08:43:20 passed: (5.8s) 2020-04-15T00:43:20 "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-24094-Default resources of Marketplace operator [Suite:openshift/conformance/parallel]"
08:43:20 
08:43:20 started: (0/4/25) "[sig-operator] an end user handle OLM to support OLM-Medium-OCP-24664-CRD updates if new schemas are backwards compatible [Suite:openshift/conformance/parallel]"
08:43:20 
08:43:45 passed: (31s) 2020-04-15T00:43:45 "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-23170-API labels should be hash [Suite:openshift/conformance/parallel]"
08:43:45 
08:43:45 started: (0/5/25) "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-24093-check the delete of operatorsource [Suite:openshift/conformance/parallel]"
08:43:45 
08:43:50 passed: (36.2s) 2020-04-15T00:43:50 "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-24904-create catalogsource with grpc address [Suite:openshift/conformance/parallel]"
08:43:50 
08:43:50 started: (0/6/25) "[sig-operator] an end user handle OLM to support OLM-Medium-OCP-22200-add minimum kube version to CSV [Suite:openshift/conformance/parallel]"
08:43:50 
08:44:12 passed: (26.5s) 2020-04-15T00:44:12 "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-24093-check the delete of operatorsource [Suite:openshift/conformance/parallel]"
08:44:12 
08:44:12 started: (0/7/25) "[sig-operator] an end user handle OLM to support OLM-Medium-OCP-23473-permit z-stream releases skipping during operator updates [Suite:openshift/conformance/parallel]"
08:44:12 
08:45:09 passed: (1m49s) 2020-04-15T00:45:09 "[sig-operator] an end user handle OLM to support OLM-Medium-OCP-24664-CRD updates if new schemas are backwards compatible [Suite:openshift/conformance/parallel]"
08:45:09 
08:45:09 started: (0/8/25) "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-21404-csv will be RequirementsNotMet after role rule is delete [Suite:openshift/conformance/parallel]"
08:45:09 
08:45:28 passed: (1m17s) 2020-04-15T00:45:28 "[sig-operator] an end user handle OLM to support OLM-Medium-OCP-23473-permit z-stream releases skipping during operator updates [Suite:openshift/conformance/parallel]"
08:45:28 
08:45:28 started: (0/9/25) "[sig-operator] an end user handle OLM common object OLM-Low-OCP-26002-allow pod of operator source on master [Suite:openshift/conformance/parallel]"
08:45:28 
08:45:38 passed: (1m48s) 2020-04-15T00:45:38 "[sig-operator] an end user handle OLM to support OLM-Medium-OCP-22200-add minimum kube version to CSV [Suite:openshift/conformance/parallel]"
08:45:38 
08:45:38 started: (0/10/25) "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-25757-High-OCP-22656-manual approval strategy apply to subsequent releases [Suite:openshift/conformance/parallel]"
08:45:38 
08:45:54 passed: (25.3s) 2020-04-15T00:45:54 "[sig-operator] an end user handle OLM common object OLM-Low-OCP-26002-allow pod of operator source on master [Suite:openshift/conformance/parallel]"
08:45:54 
08:45:54 started: (0/11/25) "[sig-operator] an end user handle OLM to support OLM-Medium-OCP-21824-verify CRD should be ready before installing the operator [Suite:openshift/conformance/parallel]"
08:45:54 
08:46:12 passed: (1m3s) 2020-04-15T00:46:12 "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-21404-csv will be RequirementsNotMet after role rule is delete [Suite:openshift/conformance/parallel]"
08:46:12 
08:46:12 started: (0/12/25) "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-24076-check the version of olm operator is appropriate in ClusterOperator [Suite:openshift/conformance/parallel]"
08:46:12 
08:46:23 passed: (11.7s) 2020-04-15T00:46:23 "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-24076-check the version of olm operator is appropriate in ClusterOperator [Suite:openshift/conformance/parallel]"
08:46:23 
08:46:23 started: (0/13/25) "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-24027-can create and delete catalogsource and sub repeatedly [Suite:openshift/conformance/parallel]"
08:46:23 
08:46:42 passed: (1m4s) 2020-04-15T00:46:42 "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-25757-High-OCP-22656-manual approval strategy apply to subsequent releases [Suite:openshift/conformance/parallel]"
08:46:42 
08:46:42 started: (0/14/25) "[sig-operator] an end user handle OLM to support OLM-High-OCP-22226-the csv without support AllNamespaces fails for og with allnamespace [Suite:openshift/conformance/parallel]"
08:46:42 
08:46:54 passed: (1m1s) 2020-04-15T00:46:54 "[sig-operator] an end user handle OLM to support OLM-Medium-OCP-21824-verify CRD should be ready before installing the operator [Suite:openshift/conformance/parallel]"
08:46:54 
08:46:54 started: (0/15/25) "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-20979-only one IP is generated [Suite:openshift/conformance/parallel]"
08:46:54 
08:47:23 passed: (41s) 2020-04-15T00:47:23 "[sig-operator] an end user handle OLM to support OLM-High-OCP-22226-the csv without support AllNamespaces fails for og with allnamespace [Suite:openshift/conformance/parallel]"
08:47:23 
08:47:23 started: (0/16/25) "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-21825-Certs for packageserver can be rotated successfully [Suite:openshift/conformance/parallel]"
08:47:23 
08:47:37 passed: (43.1s) 2020-04-15T00:47:37 "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-20979-only one IP is generated [Suite:openshift/conformance/parallel]"
08:47:37 
08:47:37 started: (0/17/25) "[sig-operator] an end user handle OLM to support OLM-High-OCP-22226-the csv without support MultiNamespace fails for og with MultiNamespace [Suite:openshift/conformance/parallel]"
08:47:37 
08:47:51 passed: (28.1s) 2020-04-15T00:47:51 "[sig-operator] an end user handle OLM common object OLM-Medium-OCP-21825-Certs for packageserver can be rotated successfully [Suite:openshift/conformance/parallel]"
08:47:51 
08:47:51 started: (0/18/25) "[sig-operator] an end user handle OLM within all namespace OLM-High-OCP-25679-Medium-OCP-21418-Cluster resource created and deleted correctly [Suite:openshift/conformance/parallel]"
08:47:51 
08:48:18 passed: (1m54s) 2020-04-15T00:48:18 "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-24027-can create and delete catalogsource and sub repeatedly [Suite:openshift/conformance/parallel]"
08:48:18 
08:48:18 started: (0/19/25) "[sig-operator] an end user handle OLM within all namespace OLM-Medium-OCP-21484-High-OCP-21532-watch special or all namespace by operator group [Suite:openshift/conformance/parallel]"
08:48:18 
08:48:29 passed: (38.3s) 2020-04-15T00:48:29 "[sig-operator] an end user handle OLM within all namespace OLM-High-OCP-25679-Medium-OCP-21418-Cluster resource created and deleted correctly [Suite:openshift/conformance/parallel]"
08:48:29 
08:48:29 started: (0/20/25) "[sig-operator] an end user handle OLM within a namespace OLM-High-OCP-24870-can not create csv without operator group [Suite:openshift/conformance/parallel]"
08:48:29 
08:48:33 passed: (55.7s) 2020-04-15T00:48:33 "[sig-operator] an end user handle OLM to support OLM-High-OCP-22226-the csv without support MultiNamespace fails for og with MultiNamespace [Suite:openshift/conformance/parallel]"
08:48:33 
08:48:33 started: (0/21/25) "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-21404-csv will be RequirementsNotMet after sa is delete [Suite:openshift/conformance/parallel]"
08:48:33 
08:48:57 passed: (39.2s) 2020-04-15T00:48:57 "[sig-operator] an end user handle OLM within all namespace OLM-Medium-OCP-21484-High-OCP-21532-watch special or all namespace by operator group [Suite:openshift/conformance/parallel]"
08:48:57 
08:48:57 started: (0/22/25) "[sig-operator] an end user handle OLM within all namespace OLM-Medium-OCP-24906-Operators requesting cluster-scoped permission can trigger kube GC bug [Suite:openshift/conformance/parallel]"
08:48:57 
08:49:13 passed: (43.4s) 2020-04-15T00:49:13 "[sig-operator] an end user handle OLM within a namespace OLM-High-OCP-24870-can not create csv without operator group [Suite:openshift/conformance/parallel]"
08:49:13 
08:49:13 started: (0/23/25) "[sig-operator] an end user handle OLM within a namespace OLM-High-OCP-25855-Add the channel field to subscription_sync_count [Suite:openshift/conformance/parallel]"
08:49:13 
08:49:20 passed: (47.1s) 2020-04-15T00:49:20 "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-21404-csv will be RequirementsNotMet after sa is delete [Suite:openshift/conformance/parallel]"
08:49:20 
08:49:20 started: (0/24/25) "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-24438-check subscription CatalogSource Status [Suite:openshift/conformance/parallel]"
08:49:20 
08:49:26 passed: (29.6s) 2020-04-15T00:49:26 "[sig-operator] an end user handle OLM within all namespace OLM-Medium-OCP-24906-Operators requesting cluster-scoped permission can trigger kube GC bug [Suite:openshift/conformance/parallel]"
08:49:26 
08:49:59 passed: (46.1s) 2020-04-15T00:49:59 "[sig-operator] an end user handle OLM within a namespace OLM-High-OCP-25855-Add the channel field to subscription_sync_count [Suite:openshift/conformance/parallel]"
08:49:59 
08:50:01 passed: (40.9s) 2020-04-15T00:50:01 "[sig-operator] an end user handle OLM within a namespace OLM-Medium-OCP-24438-check subscription CatalogSource Status [Suite:openshift/conformance/parallel]"
08:50:01 
08:50:01 started: (0/25/25) "[sig-operator] an end user handle OLM within all namespace OLM-High-OCP-25783-Subscriptions are not getting processed taking very long to get processed [Serial] [Suite:openshift/conformance/serial]"
08:50:01 
08:51:35 passed: (1m34s) 2020-04-15T00:51:35 "[sig-operator] an end user handle OLM within all namespace OLM-High-OCP-25783-Subscriptions are not getting processed taking very long to get processed [Serial] [Suite:openshift/conformance/serial]"
```

**Comment by jianzhangbjz** [comment]
Details logs in http://10.0.96.174:8080/job/olm-test/204/console  and http://10.0.96.174:8080/job/olm-test/203/console

**Pull request merged**
